version: '2'
services:
    jhipster-app:
        image: jhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=jhipster-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    jhipster-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: jhipster-cassandra
    jhipster-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=jhipster-cassandra
    jhipster-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: jhipster-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
